### ISSUE TITLE
renderer/index.html are not packed into dist

### ISSUE THREAD

**Issue by TianQingshuai** [xiefengnian/umijs-electron-template#1]
.electron-production/render/index.html was generated after electron-builder task.
![image](https://user-images.githubusercontent.com/17986611/231726373-5f3bd2d6-26ba-42ed-8c05-fb767217b4b0.png)
![image](https://user-images.githubusercontent.com/17986611/231726560-fae811d9-b05c-4c20-abc0-4e2a37c10603.png)

**Comment by xiefengnian** [comment]
感谢，已经发布0.2.3的plugin修复了这个问题
