### ISSUE TITLE
参考umi官方文档pnpm create umi --template electron 运行时报错

### ISSUE THREAD

**Issue by lmh1341** [xiefengnian/umijs-electron-template#2]
$ npm run start
Debugger attached.

> @umijs/electron-template@1.0.1 start
> npm run dev

Debugger attached.

> @umijs/electron-template@1.0.1 dev
> umi dev

Debugger attached.
Debugger attached.
info  - [你知道吗？] umi g tsconfig 可一键完成项目的 TypeScript 配置。
info  - Umi v4.0.67
info  - Preparing...
info  - MFSU eager strategy enabled
info  - [MFSU][eager] restored cache
event - [MFSU][eager] start build deps
info  - [MFSU] skip buildDeps
        ╔════════════════════════════════════════════════════╗
        ║ App listening at:                                  ║
        ║  >   Local: http://localhost:8001                  ║
ready - ║  > Network: http://30.178.80.50:8001               ║
        ║                                                    ║
        ║ Now you can open browser with the above addresses↑ ║
        ╚════════════════════════════════════════════════════╝
event - [Webpack] Compiled in 895 ms (314 modules)
[dev] src: /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main, output: /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/.electron/dist
wait  - [Webpack] Compiling...
event - [MFSU][eager] start build deps
info  - [MFSU] skip buildDeps
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/index.ts
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/preload.ts
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/tsconfig.json
[ignore] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/tsconfig.json
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/typing.d.ts
[ignore] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/typing.d.ts
info  - [MFSU][eager] worker init, takes 985ms
event - [Webpack] Compiled in 600 ms (314 modules)
[init] /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/src/main/ipc/platform.ts
Debugger attached.
App threw an error during load
Error: Cannot find module 'clear-module'
Require stack:
- /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/.electron/entry.js
- /Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/node_modules/.store/electron@21.4.4/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/markleo/Desktop/Test/electron/electron-umimax4-demoe-04/.electron/entry.js:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)

**Comment by unrealsmart** [comment]
**安装 `pnpm install clear-module lodash chokidar` 并重新运行时，你将获得成功！**

特别提醒：
```
export default defineConfig({
  npmClient: 'yarn',
  plugins: ['@umijs/plugin-electron'],
  electron: {
    builder: {
      targets: Platform.MAC.createTarget(['dmg'], Arch.arm64),
    },
  },
});
```
将`npmClient`修改为你的包管理工具，比如：`npm` `pnpm`等
注意`Platform.MAC`，修改为你的系统，比如：`Platform.WINDOWS` `Platform.LINUX`

**Comment by xiefengnian** [comment]
> **安装 `pnpm install clear-module lodash chokidar` 并重新运行时，你将获得成功！**
> 
> 特别提醒：
> 
> ```
> export default defineConfig({
>   npmClient: 'yarn',
>   plugins: ['@umijs/plugin-electron'],
>   electron: {
>     builder: {
>       targets: Platform.MAC.createTarget(['dmg'], Arch.arm64),
>     },
>   },
> });
> ```
> 
> 将`npmClient`修改为你的包管理工具，比如：`npm` `pnpm`等 注意`Platform.MAC`，修改为你的系统，比如：`Platform.WINDOWS` `Platform.LINUX`

是的，pnpm不允许幽灵依赖，所以使用pnpm时需要自己安装这几个包
